import Head from "next/head";
import Image from "next/image";
import Container from "../components/Container";

export default function Home() {
  return (
    <div className="bg-slate-900 h-screen w-screen">
      <Head>
        <title>Age Calculator</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="w-screen h-screen flex lg:items-center justify-center">
        <Container />
      </main>
    </div>
  );
}
